make apps install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -71,17 +71,113 @@ function display_packages {
     fi
 }
 
+cat << EOF
+Do you want to install the following packages:
+$(display_packages)
+EOF
+    while true; do
+        read -rp "Do you want to install the above packages? (y/n) " yn
+        case "${yn}" in
+            [Yy]*)
+                if [ "${os_type}" == "Linux" ]; then
+                    apt_install_packages
+                else
+                    brew_install_packages
+                fi
+
+                break;;
+            [Nn]*) exit 0;;
+            *) echo "Please answer y or n";;
+        esac
+    done
+
+
 function install_oh_my_zsh {
-    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
+    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended || true
 }
 
+install_oh_my_zsh
+
+git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k || true
+
+git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting || true
+
 ###############################################################################
-# Install zsh plugins
+# Clone dotfiles
 ###############################################################################
+
+read -rep $'\nWhere do you want to clone these dotfiles to [~/dotfiles]? ' clone_path
+clone_path="${clone_path:-"${HOME}/dotfiles"}"
+
+# Ensure path doesn't exist.
+while [ -e "${clone_path}" ]; do
+    read -rep $'\nPath exists, try again? (y) ' y
+    case "${y}" in
+        [Yy]*)
+
+            break;;
+        *) echo "Please answer y or CTRL+c the script to abort everything";;
+    esac
+done
+
+echo
+
+# This is used to locally develop the install script.
+if [ "${DEBUG}" == "1" ]; then
+    cp -R "${PWD}/." "${clone_path}"
+else
+    git clone https://github.com/joshwrn/dotfiles "${clone_path}"
+fi
+
+###############################################################################
+# Create initial directories
+###############################################################################
+
+mkdir -p "${HOME}/.config/zsh" "${HOME}/.config/nvim"
+
+cat << EOF
+-------------------------------------------------------------------------------
+files will be linked from "${clone_path}" to "${HOME}"
+# And if you happen to be using WSL:
+sudo ln -fs "${clone_path}/etc/wsl.conf" /etc/wsl.conf
+-------------------------------------------------------------------------------
+A potentially dangerous action is about to happen. The above files are going to
+get forcefully symlinked.
+What does that mean?
+Any config files you have on the right hand side of the paths are going to get
+overwritten with the files that come with my dotfiles (left side).
+If you care about your original config files now would be the time to back
+them up. They will ALL be overwritten if you say yes to the prompt below.
+EOF
+
+while true; do
+  read -rep $'\nReady to continue and apply the symlinks? (y) ' y
+  case "${y}" in
+      [Yy]*)
+
+          break;;
+      *) echo "Please answer y or CTRL+c the script to abort everything";;
+  esac
+done
+
+ln -fs "${clone_path}/.zshenv" "${HOME}/.zshenv" \
+    && ln -fs "${clone_path}/.zshrc" "${HOME}/.zshrc" \
+    && ln -fs "${clone_path}/.p10k.zsh" "${HOME}/.p10k.zsh" \
+    && ln -fs "${clone_path}/.bashrc" "${HOME}/.bashrc" \
+    && ln -fs "${clone_path}/.fzf.zsh" "${HOME}/.fzf.zsh" \
+    && ln -fs "${clone_path}/.fzf" "${HOME}" \
+    && ln -fs "${clone_path}/.config/nvim/init.vim" "${HOME}/.config/nvim/init.vim" \
+
+if grep -qE "(Microsoft|microsoft|WSL)" /proc/version &>/dev/null; then
+    sudo ln -fs "${clone_path}/etc/wsl.conf" /etc/wsl.conf
+fi
+
 
 ###############################################################################
 # Done!
 ###############################################################################
+
+
 
 cat << EOF
 Everything was installed successfully!
